name: Test contracts sdk
on: [pull_request]

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.11.0 ]
    outputs:
      runner: ${{ steps.branch.outputs.runner }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies and authenticate
        run: |
          npm install

      - name: Test sdk
        continue-on-error: false 
        run: |
           npm run build
           npm run test
